### ISSUE TITLE
<AdParameters> not being parsed

### ISSUE THREAD

**Issue by Fire-Brand** [jonhoo/vast-vmap#18]
Hi,
With the big change of dropping Flash in the browser world, the Javascript VPAID format is gaining popularity.

In a lot of VAST xml ads i can find the ```<AdParameters>``` tag (usualy as a JSON object).
Is it possible to please add the code and add it to the VASTLiner object?

**Comment by jonhoo** [comment]
Yes, this shouldn't be too complicated an addition. However, as I do not use vast-vmap myself, I am hesitant to implement it myself, as I cannot reliably test how it works in the real world. PRs are welcome, and I will happily review them. Please also include appropriate tests. If `<AdParameters>` is indeed a sub-tag of `VastLinear` (and no other elements), this should be added at https://github.com/jonhoo/vast-vmap/blob/master/src/vast-vmap.js#L1083. It would also be good to link to the part of the standard that mentions `<AdParameters>` from this issue.

**Comment by Fire-Brand** [comment]
Hi @jonhoo , i am currently working with vast-vmap (well, with the vast part to be more precise) but unfortunately don't have the time to write a PR with tests and everything right now, and would be glad if someone could tend to this.

about the IAB standard, in the [VAST 3.0 docs](http://www.iab.net/media/file/VASTv3.0.pdf#page=34) (page 34) you can find the following section: **2.3.1.10 The Optional <AdParameters> Element** which state that ```<AdParameters>``` is one of four optional elements under the ```<Linear>``` element.

**Comment by Fire-Brand** [comment]
It seemed i had no choice but to add the ```<AdParameters>``` functionality so i did, sorry for not having the time to create the proper tests, here is what i added in short:

**VASTCreative** function is now:

```javascript
function VASTCreative(ad, root) {
  this.root = root;
  this.clickThrough = null;
  this.adParameters = null; // Added by Fire-Brand
  if (root.tagName === "NonLinear") {
    root = root.parentNode;
  }
  this.tracking = new TrackingEvents(root, ad);
}
```

and **VASTLinear** function is now:

```javascript
function VASTLinear(ad, root) {
  VASTCreative.call(this, ad, root);
  this.mediaFiles = [];
  this.clickThrough = null;
  this.duration = null;
  this.adParameters = null;

  var i;

  var clicks = root.getElementsByTagName("VideoClicks");
  if (clicks.length) {
    clicks = clicks.item(0);
    var ct = clicks.getElementsByTagName("ClickThrough");
    if (ct.length) {
      this.clickThrough = ct.item(0).textContent.replace(/\s/g, "");
    }

    ct = clicks.getElementsByTagName("ClickTracking");
    for (i = 0; i < ct.length; i++) {
      this.tracking.addClickTracking(ct.item(i).textContent.replace(/\s/g, ""));
    }
  }

  var d = root.getElementsByTagName("Duration");
  if (d.length) {
    this.duration = this.timecodeFromString(d.item(0).textContent.replace(/\s/g, ""));
  }

 /////////////////////////////////////////////////////////// Added by FireBrand
  var ap = root.getElementsByTagName("AdParameters");
  if(ap.length){
    this.AdParameters = ap.item(0).textContent.replace(/\s/g, "");
  }
 /////////////////////////////////////////////////////////// Added by FireBrand

  var medias = root.getElementsByTagName("MediaFiles");
  if (!medias.length) {
    return;
  }

  medias = medias.item(0).getElementsByTagName("MediaFile");
  for (i = 0; i < medias.length; i++) {
    var m = medias.item(i);
    var mf = {};
    for (var a = 0; a < m.attributes.length; a++) {
      mf[m.attributes[a].name] = m.attributes[a].value;
    }
    mf["src"] = medias.item(i).textContent.replace(/\s/g, "");
    this.mediaFiles.push(mf);
  }
}
```

It seems to work and add the AdParameters object as a string to the VASTLinear Obj

**Comment by Fire-Brand** [comment]
My Bad i was hiding my own player right before i launched the AdUnit, this can be closed

**Comment by jonhoo** [comment]
How is that related to the feature request? And why does it resolve it?

I don't think the change to `VASTCreative` is necessary. `this.AdParameters` also be `this.adParameters`

**Comment by Fire-Brand** [comment]
It doesn't have anything to with my issue, i mixed this issue with something else i've being working on... My bad 😀.

Regarding your comments: yeah you are right about both of them and i'll change it in my code.
