### ISSUE TITLE
New Chrome has no 'namespaceURI'

### ISSUE THREAD

**Issue by Fire-Brand** [jonhoo/vast-vmap#19]
My google Chrome just got updated to version **46.0.2490.71 m** (latest at the moment) and suddenly all my ads ware gone (while on FireFox it still works well) , from a quick debug i found that on the ```VASTAds``` constructor (line ```420```) the ```adElement``` variable is empty after line ```425``` : 
```javascript
  var adElements = root.getElementsByTagNameNS(root.namespaceURI, 'Ad');
```
I've noticed that ```namespaceURI``` is undefined on Chrome,
on FireFox it is ```null``` and ```adElement``` is not empty after line ```425``` and  has the ad in it.

any idea what might cause this and how to fix it?

**Comment by Fire-Brand** [comment]
It seems that the new chrome has an issue with ```getElementsByTagNameNS```

changing line 425 from:
``javascript
  var adElements = root.getElementsByTagNameNS(root.namespaceURI, 'Ad');
```
to:
``javascript
  var adElements = root.getElementsByTagNameNS("*", 'Ad');
```

solves the issue and function well on Chrome and on FireFox aswell, @jonhoo do you think this is valid?

**Comment by jonhoo** [comment]
Yes, I suppose that would work. Send a PR and I'll merge?

**Comment by Fire-Brand** [comment]
will do so as soon as i can
