### ISSUE TITLE
Ad tag macros

### ISSUE THREAD

**Issue by Fire-Brand** [jonhoo/vast-vmap#25]
Most of the tags i see these days are VPAID (Flash/JS) and look somthing like this:

``` http://ads.somesite.advertising.com/ad?cb=[CACHE_BUSTER]&pageUrl=[URL]&description=[VIDEO_DESCRIPTION]&duration=[VIDEO_DURATION]&id=[VIDEO_ID]&keywords=&title=[VIDEO_TITLE]&url=[VIDEO_FILE_URL] ```

All these macros need to be filled as best as possible in order for the ad server to return the most comprehensive VAST xml file it can, i thought about writing a function that would do just that, but i'm not sure if it should be a part of the ```VAST-VMAP``` library or a stand-alone function, any ideas?

**Comment by jonhoo** [comment]
I think this should probably be separate from VAST-VMAP, as it seems provider dependent, and requires information about the video being played, and not the ad itself.

**Comment by Fire-Brand** [comment]
I see what you're saying, i think i'm gonna try and do it as generic as i can, see if it could resemble the ```track(ev, _macros)``` function so it would work with whatever fields the object you give it has, i'll post it here once i'm done.

**Comment by Fire-Brand** [comment]
So, i went and wrote the function, basically its just taking the relevant parts out of ```track(ev, _macros)``` and use the returned URL in ```queryVAST``` function.

Here it is:

```javascript
// takes the given URL and substitute the Macros placeholders with data
// regarding the video-player and the content
function injectMacrosInAdTag(adTag, _macros) {
  var macros = {};
  for (var m in _macros) {
    if (!_macros.hasOwnProperty(m)) {
      continue;
    }

    macros["[" + m + "]"] = encodeURIComponent(_macros[m]);
  }

  // Standard dictates 8 digits of randomness
  var rand = '' + parseInt(Math.random() * 99999999, 10);
  while (rand.length !== 8) {
    rand = '0' + rand;
  }
  macros["[CACHEBUSTING]"] = rand;

  for (m in macros) {
    if (!macros.hasOwnProperty(m)) {
      continue;
    }
    adTag = adTag.replace(m, macros[m]);
  }

  return adTag;
}
```

Gonna put it here in case anyone ever needs this functionality.

**Comment by jonhoo** [comment]
Seems like a useful function, but again, I don't think it's something that should be included in VAST-VMAP. Thanks for sharing nonetheless!
