### ISSUE TITLE
Checking if tag is VPAID or Non-VPAID

### ISSUE THREAD

**Issue by byangcs** [jonhoo/vast-vmap#32]
I first would like to say that your vast-parser is awesome and easy to use. 

I was wondering if there's a check in your code for whether the tag is VPAID. I'm implementing a bundle that parses the VAST tag only if it's non-VPAID and it'd be helpful if that functionality is implemented somewhere already.

**Comment by jonhoo** [comment]
Glad you find the library useful!
There is nothing currently in there to deal with VPAID specifically, though if you need access to any of the same things as @Fire-Brand in #18, maybe the change in c8c55053502117c4198bafde2b0ffe83b8ba3e09 will help you.

**Comment by byangcs** [comment]
Thanks! It helps.
