### ISSUE TITLE
Dynamic `window[cls]` constructor generation fails when `vast-vmap` runs within a function scope. 

### ISSUE THREAD

**Issue by sterpe** [jonhoo/vast-vmap#37]
So what I am doing is injecting VAST-VMAP into the DOM via Flash `ExternalInterface.call` and wrapping _it_ in an anonymous function that looks basically like this:

```javascript
!function (url) {
  <% = vast-vmap.js %>
  ;function onSuccess () { /* code here */}
  ;function onFailure () {/* code here */}
  ;queryVAST(url, onSuccess, onFailure)
}("http://some.vast.server.com/foo.xml")
```
And this is just to avoid polluting the containing document global space and other weirdness.

This is all fine, until [L797](https://github.com/jonhoo/vast-vmap/blob/master/src/vast-vmap.js#L797) and [L811](https://github.com/jonhoo/vast-vmap/blob/master/src/vast-vmap.js#L811):

```javascript
var cls = tag === "Companion" ? "VASTCompanion" : "VASTNonLinear";
// ...
 n = new window[cls](this, items.item(j));
```

Which then fails because these are not defined on the global scope.

I'd like to put in a PR to change these two lines to use the function references in the scope, wherever that may be.

```javascript
var cls = tag === "Companion" ? VASTCompanion : VASTNonLinear;
// ...
n = new cls(this, items.item(j));
```

**Comment by jonhoo** [comment]
I'm not sure that will actually work -- I think the JavaScript engine will complain that the type `cls` doesn't exist -- this is exactly why I did it this way. If you way works though, that's great. I think the cleanest solution I've seen to this is [introducing a `namespace` object](http://stackoverflow.com/a/9804142/472927).

**Comment by sterpe** [comment]
We probably should introduce a ns.  It would be a breaking change, though.  But yeah, js is okay with assigning a constructor to another variable and referencing it that way...that assignment won't be hoisted to the top of scope though like the constructor declaration will.

**Comment by jonhoo** [comment]
Oh, interesting -- I was so sure the approach above would fail that I didn't even try it. If it works the way you describe, then this change should be trivial.

As for namespacing, exposing this as a project JS module is a good idea. I think vast-vmap should really be exposed as a RequireJS module, and preferably we should start actually using version numbers such that breaking changes like this aren't such a hassle.

**Comment by sterpe** [comment]
The namespace problem seems to be sort of related to #1.

I could go either way.  Here's how I'm currently using vast-vmap: build a javascript bundle via `browserify`, set up a global shim with the `browserify-shim` transform so that I can do things like this in my code:  `var queryVAST = require('query-vast')`  (This gets rewritten to `var queryVAST = window.queryVAST`, essentially.)  Then I literally just `cat node_modules/vast-vmap/src/vast-vmap.js bundle.js > final.js`.

I use `npm install jonhoo/vast-vmap` which pull the repo into my `node_modules` folder, but I maintain my own public fork, and we have a mirror inside our own engineering network as well, when we need to  get ahead of this repo.  

Have you thought about a UMD wrapper?  That would work with requireJS/AMD or a CommonJS module loader (like node/browserify) and globally if necessary in a `<script>` tag.  Then you could put the same file on `npm` and `bower` with versioning.

**Comment by jonhoo** [comment]
Using UMD seems like a good way to go. Hopefully that'd simplify your workflow somewhat too. I don't have a lot of spare time to devote to this project atm, but I'd be happy to take a look if you take a stab at it.

**Comment by sterpe** [comment]
Fair enough.  It's not a huge priority for me at the moment, but I'll take a look if I have some time in the future.
