### ISSUE TITLE
Handle empty vast response (no ads)

### ISSUE THREAD

**Issue by yanivefraim** [jonhoo/vast-vmap#8]
According to iab spec (vast 3.0, section 2.4.2.4):

When the ad server does not or cannot return!an Ad, the VAST response should contain only the root \<VAST\> element with optional \<Error\> element, as shown below:
 ````xml
<VAST version=”3.0”>
    <Error>
        <![CDATA[http://adserver.com/noad.gif]>
</Error>
</VAST>
````

The issue in our case, which is related to issue #7 is that when there are no ads, the 'onAdsAvailable' callback is not triggered.

The solution should contain both handling 'no ads' and adding the "error" element to the callback response (so the user will be able to fire this error pixel).

Regarding "no ads" callback there are two possible solutions: 
1. Trigger the same "onAdsAvailable" callback, with no ads. The user should validate the response and check for available ads
2. Trigger a different error callback

I will be happy to assist & add a solution here.

tnx!

**Comment by jonhoo** [comment]
I believe this is fixed by 018ba4f9d4be4215526e614cd13646f29094106f /  #13.
